from flask import Flask, render_template
import random

app = Flask(__name__)

quotes = [
    "It is humiliating to remain with our hands folded while others write history. It matters little who wins. - Benito Mussolini",
    "To make a people great it is necessary to send them to battle even if you have to kick them in the pants. That is what I shall do. - Benito Mussolini",
    "Every soldier must know, before he goes into battle, how the little battle he is to fight fits into the larger picture. - Bernard L. Montgomery",
    "If we lose the war in the air we lose the war and we lose it quickly. - Bernard L. Montgomery",
    "It's good to trust others, but, not to do so is much better. - Benito Mussolini",
    "From a philosophical and doctrinal viewpoint, I do not believe in perpetual peace. - Benito Mussolini",
    "Giraffes are heartless creatures",
    "As long as there are sovereign nations possessing great power, war is inevitable. - Albert Einstein",
    "Those who vote decide nothing. Those who count the vote decide everything. - Joseph Stalin",
    "History shows that there are no invincible armies and that there never have been. - Joseph Stalin",
    "The Pope! How many divisions has he got? - Joseph Stalin",
    "Gaiety is the most outstanding feature of the Soviet Union. - Joseph Stalin",
    "The only real power comes out of a long rifle. - Joseph Stalin",
    "Any alliance whose purpose is not the intention to wage war is senseless and useless. - Adolf Hitler",
    "Great liars are also great magicians. - Adolf Hitler",
    "If today I stand here as a revolutionary, it is as a revolutionary against the Revolution. - Adolf Hitler",
    "If you tell a big enough lie and tell it frequently enough, it will be believed. - Adolf Hitler",
    "Germany will either be a world power or will not be at all. - Adolf Hitler",
    "Success consists of going from failure to failure without loss of enthusiasm. - Winston Churchill",
    "If you're going through hell, keep going. - Winston Churchill",
    "The best argument against democracy is a five-minute conversation with the average voter. - Winston Churchill",
    "Whenever in future wars the battle is fought, panzer troops will play the decisive role. - Heinz Guderian",
    "The new German Panther and Tiger can be used until they break down without trying to repair them. They have bad engines, transmission and suspension. - Department of Weaponry of the Red Army",
    "No bastard ever won a war by dying for his country. He won it by making the other poor dumb bastard die for his country. - George S. Patton",
    "A good plan violently executed now is better than a perfect plan executed next week. - George S. Patton",
    "Lead me, follow me, or get out of my way. - George S. Patton",
    "Nobody ever defended anything successfully, there is only attack and attack and attack some more. - George S. Patton",
    "Wars may be fought with weapons, but they are won by men. It is the spirit of men who follow and of the man who leads that gains the victory. - George S. Patton",
    "The first time I ever saw a jet, I shot it down. - Chuck Yeager, USAAF",
    "Theo, Heinrich here. Have just shot down two bombers. No more ammunition. I'm going to ram. Auf Wiedersehen, see you in Valhalla! - Heinrich Ehrler, Luftwaffe",
    "Leadership consists of picking good men and helping them do their best. - Chester W. Nimitz",
    "Is the proposed operation likely to succeed? Is it in the realm of practicability in terms of material and supplies? - Chester W. Nimitz",
    "In preparing for battle I have always found that plans are useless, but planning is indispensable. - Dwight D. Eisenhower",
    "What counts is not necessarily the size of the dog in the fight - it's the size of the fight in the dog. - Dwight D. Eisenhower",
    "It goes without saying that when survival is threatened, struggles erupt between peoples, and unfortunate wars between nations result. - Hideki Tojo",
    "In a man-to-man fight, the winner is he who has one more round in his magazine. - Erwin Rommel",
    "I would rather be the hammer than the anvil. - Erwin Rommel",
    "Sweat saves blood, blood saves lives, but brains saves both. - Erwin Rommel",
    "Poor Neville Chamberlain believed he could trust Hitler. He was wrong. But I don't think I'm wrong about Stalin. - Winston Churchill, after the Yalta Conference",
    "I believe it is peace for our time. - Neville Chamberlain, 1938 after Munich agreement.",
    "No enemy bomber can reach the Ruhr. If one reaches the Ruhr, my name is not Göring. You may call me Meyer. - Hermann Meyer",
    "We have only to kick in the door and the whole rotten structure will come crashing down. - Adolf Hitler (on the Soviet Union)",
    "I can run wild for the first six to twelve months of a war with the United States and the United Kingdom. After that, I have no expectation of success. - Isoroku Yamamoto",
    "If we come to a minefield, our infantry attacks exactly as if it were not there. - Georgy Zhukov",
    "The Russian colossus has been underestimated by us... whenever a dozen divisions are destroyed, the Russians replace them with another dozen. - Franz Halder",
    "NUTS! - Anthony C. McAuliffe, responding to the German demand for surrender",
    "It is us today. It will be you tomorrow. - Haile Selassie I, 1936",
    "Not one step back! - Soviet Order No. 227",
    "Tora! Tora! Tora! - Mitsuo Fuchida, 7 December, 1941",
    "Your name is unknown. Your deed is immortal. - Tomb of the Unknown Soldier (Moscow)",
    "Where is, repeat, where is Task Force Thirty-Four? The world wonders. - CINCPAC, Battle of Leyte Gulf",
    "The war situation has developed not necessarily to Japan's advantage. - Emperor Hirohito, 1945",
    "We should have known better after the first war. - Gerd von Rundstedt",
    "The vastness of Russia devours us. - Gerd von Rundstedt",
    "I ask you, do you want total war? If necessary, do you want a war more total and radical than anything that we can even yet imagine? - Joseph Goebbels",
    "One blow from the German army and another from the Soviet army put an end to this ugly product of Versailles. - Vyacheslav Molotov (after the fall of Poland)",
    "Scratch one flattop! Dixon to carrier: scratch one flattop! - Robert E. Dixon, Battle of the Coral Sea",
    "Isn't it dreadful? Here we are, two officers of the German General Staff, discussing how best to murder our commander in chief. - Henning von Tresckow",
    "Hitler is a dancing dervish. He must be shot down. - Henning von Tresckow",
    "The Nazis entered this war under the rather childish delusion that they were going to bomb everyone else, and nobody was going to bomb them. - Arthur 'Bomber' Harris",
    "If Hitler invaded Hell, I would make at least a favorable reference to the devil in the House of Commons. - Winston Churchill, 21 June, 1941",
    "So the bastard's dead? Too bad we didn't capture him alive! - Joseph Stalin (on hearing of Hitler's suicide)",
    "We have been defeated. We are beaten, we have lost the battle. - Paul Reynaud, 15 May, 1940",
    "I only need a few thousand dead so that I can sit at the peace conference as a man who has fought. - Benito Mussolini",
    "The French had lied to the Poles in saying they are going to attack. There is no idea of it. - Edmund Ironside",
    "Why Die for Danzig? - French Anti-War Slogan, 1939",
    "There is something phoney about this war. - US Senator William Borah, 1939",
    "Switzerland possessesthe most disgusting and miserable people and political system. The Swiss are the mortal enemies of the new Germany. - Adolf Hitler",
    "The fruits of victory are tumbling into our mouths too quickly. - Emperor Hirohito", 
    "You will all wind up shining the shoes of the Germans! - Italo Balbo",
    "Sink, burn, capture, destroy. Let nothing pass. - Andrew Cunningham, Battle of Tunisia",
    "I think we may be going a bridge too far. - Frederick Browning (prior to Operation Market Garden)",
    "Thank God for the French Army. - Winston Churchill, 1933",
    "When you see a rattlesnake poised to strike, you do not wait until he has struck to crush him. - Franklin D. Roosevelt",
    "Rules are not necessarily sacred, principles are. - Franklin D. Roosevelt",
    "People who are hungry and out of a job are the stuff of which dictatorships are made. - Franklin D. Roosevelt",
    "A man has to be alert all the time if he expects to keep on breathing. If not, some German son-of-a-bitch will sneak up behind him and beat him to death with a sock full of shit. - George S. Patton",
    "Fortifications, artillery, foreign aid - will be of no value, unless the ordinary soldier knows that it is HE guarding his country. - Carl Gustaf Emil Mannerheim",
    "Through the mud and the blood to the green fields beyond. - Royal Canadian Armoured Corps motto",
    "There is general curiosity in the British Fleet to find out whether the Italians are up to the level they were at in the last war or whether they have fallen off at all. - Winston Churchill (on the Italian declaration of war)", 
    "And we'll fight them with the butt ends of broken beer bottles because that's bloody well all we've got! - Winston Churchill (immediately after promising to fight in the fields and in the streets)",
    "Experience has shown that attacks against tanks with close combat weapons by a sufficiently determined man will basically always succeed - German Army Group Center anti-tank manual",
    "Give me fifty DC-3s and the Japanese can have the Burma Road. - Chiang Kai-Shek",
    "Politics is war without bloodshed, while war is politics with bloodshed. - Mao Zedong",
    "Keep men, lose land: land can be taken again. Keep land, lose men: land and men are both lost. - Mao Zedong",
    "I would rather die in a swamp of Greater Romania than in a paradise of a small Romania. - Ion Antonescu",
    "People don't matter, only what they represent. - Ion Antonescu",
    "In wartime, truth is so precious that she should always be attended by a bodyguard of lies. - Winston Churchill",
    "Vanquished today by mechanical force, in the future we will be able to overcome by a superior mechanical force. The fate of the world depends on it. - Charles de Gaulle",
    "The long sobs of violins of autumn. Soothe my heart with a monotone languor. - SOE coded transmission to French resistance",
    "A state like Switzerland, which is nothing but a pimple on the face of Europe, cannot be allowed to continue. - Adolf Hitler",
    "Those who can win a war well can rarely make a good peace, and those who could make a good peace would never have won the war. - Winston Churchill",
    "An appeaser is one who feeds a crocodile, hoping it will eat him last. - Winston Churchill",
    "Whoever said the pen is mightier than the sword obviously never encountered automatic weapons. - Douglas MacArthur", 
    "Either I will be decorated or I will be court martialled. Fire! - Birger Eriksen",
    "In waking a tiger, use a long stick. - Mao Zedong",
    "If everybody is thinking alike, then somebody isn't thinking. - George S. Patton",
    "We could do with some of those razor blades, Herr Reichsmarschall. - Erwin Rommel, after Göring claimed the Americans only know how to make razor blades",
    "I cannot forecast to you the action of Russia. It is a riddle wrapped in a mystery inside an enigma. - Winston Churchill",
    "However beautiful the strategy, you should occasionally look at the results. - Winston Churchill",
    "Since the Italian-Greek war, one does not say 'the Greeks are fighting like heroes', but 'the heroes are fighting like Greeks'. - The Montreal Daily Star, 1942",
    "Patriotism is when love for your people comes first. Nationalism is when hate for other people than your own comes first. - Charles de Gaulle",
    "It must be a peace without victory. Victory would mean peace forced upon the loser, a victor's terms imposed upon the vanquished. It would be accepted in humiliation and leave resentment. - Woodrow Wilson, 1917",
    "If you want total security, go to prison. There you're fed, clothed, given medical care and so on. The only thing lacking is freedom. - Dwight D. Eisenhower",
    "An army is a team. It lives, eats, sleeps, and fights as a team. This individual hero stuff is bullshit. - George S. Patton",
    "Never tell people how to do things. Tell them what to do, and they will surprise you with their ingenuity. - George S. Patton",
    "All men are frightened. The more intelligent they are, the more they are frightened. - George S. Patton",
    "Human kindness has never weakened the stamina or softened the fiber of a free people. A nation does not have to be cruel in order to be tough. - Franklin D. Roosevelt",
    "A sincere diplomat is like dry water or wooden iron. - Joseph Stalin",
    "Throughout history, it has been the inaction of those who could have acted; the indifference of those who should have known better; that has made it possible for evil to triumph. - Haile Selassie I",
    "Warsaw is not waiting for empty words of praise, for expressions of recognition, not for assurances of sympathy. Warsaw is waiting for weapons and ammunition. - Józef Piłsudski",
    "Ignorance and obscurantism have never produced anything other than flocks of slaves for tyranny. - Emiliano Zapata",
    "I'd rather die on my feet, than live on my knees. - Emiliano Zapata",
    "Gentlemen, you have fought like lions and been led by donkeys. - Erwin Rommel, to captured British officers during the siege of Tobruk",
    "The trouble with free elections is that you never know how they are going to turn out. - Vyacheslav Molotov",
    "What does the corpse care who was right and who was wrong? - Manuel Azana",
    "Your task will not be an easy one. Your enemy is well trained, well equipped, and battle-hardened. He will fight savagely. - Dwight D. Eisenhower, June 1944",
    "The quickest way of ending a war is to lose it. - George Orwell",
    "We do not want any more electoral fraud, nor more lies. We do not want that those who do not work live from those who do. - Juan Perón",
    "There's the bloody Scheer! Open fire at her! - Frederick Secker Bell",
    "We must not be defeated by the fear of the very danger which we are preparing to resist. The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
    "Our freedom has shown its ability to survive war, but our freedom would never survive surrender. - Franklin D. Roosevelt"
]

@app.route('/')
def get_output():
    selquote = random.choice(quotes)

    return render_template('main.html', script_output=selquote)

if __name__ == '__main__':
    app.run(debug=True)
